# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pQalN8iNGxvJoPQYvsGDVdyyS+/utxPlHSx75ksCwBhajJUuQKvRGyhjqlVuImKX3Xo5RF5G785KjHYQY/lSZIcfM27xbMbhXUSPDYnYTlA8WxzXd/b7Mi3B2yWUxFOViMSAMNtubz3pwtpRVVwH4DQEtrNjbdIdNySR97ecfhCpAoDEKsc3iX1rS3+BvHjrdFiHxkz0+KdfJ/ct2FgTi5XU1wBrca672ER2AJK6oAcQ257jOCYBsbZw1Cp/gfrskPLrLvtqd7Lc9px9JMzeSZU8Ri+7Yfl7urQ7QhXiPnE9QRjnf4ad1lgK18aHwZRokL27auIV6eRuurFWQKXrGq4cDAIltEjCQnsfQU/Tt4xfNI8HZhfkEyMnwaGs1nYgKUIj9582gTq/xBuC0CiB/kI+Ao/Bln0LDIn8gzGDVfUew/J78X0jVUtDiBFvblU1f4KmZAwGFNMHOyco9DujxAuAkqGB2W6XOO4AFwA83aZcu8UjiN0nNaTyau/b5NNyigOcgZjVN0DviFR7qj/k6MGUabEKbsPLBYUDhjD4WfGgJTsu2HdgWGSqgE4G8g09nkO7pO7BZ1WGRZsRiLMqGqVBYB5BFgsFlh7KJtSWl1pKLCtvFMfU/eLVO3iRcVPPZaxUOsqp6hQ5vkgwqc+waUoOLcpSJsvymGuLkoS9gis="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
