appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pQalN8iNGxvJoPQYvsGDVdyyS+/utxPlHSx75ksCwBhajJUuQKvRGyhjqlVuImKX3Xo5RF5G785KjHYQY/lSZIcfM27xbMbhXUSPDYnYTlA8WxzXd/b7Mi3B2yWUxFOViMSAMNtubz3pwtpRVVwH4DQEtrNjbdIdNySR97ecfhCpAoDEKsc3iX1rS3+BvHjrdFiHxkz0+KdfJ/ct2FgTi5XU1wBrca672ER2AJK6oAcQ257jOCYBsbZw1Cp/gfrskPLrLvtqd7Lc9px9JMzeSZU8Ri+7Yfl7urQ7QhXiPnE9QRjnf4ad1lgK18aHwZRokL27auIV6eRuurFWQKXrGq4cDAIltEjCQnsfQU/Tt4xfNI8HZhfkEyMnwaGs1nYgKUIj9582gTq/xBuC0CiB/kI+Ao/Bln0LDIn8gzGDVfUew/J78X0jVUtDiBFvblU1f4KmZAwGFNMHOyco9DujxAuAkqGB2W6XOO4AFwA83aZcu8UjiN0nNaTyau/b5NNyigOcgZjVN0DviFR7qj/k6MGUabEKbsPLBYUDhjD4WfGgJTsu2HdgWGSqgE4G8g09nkO7pO7BZ1WGRZsRiLMqGqVBYB5BFgsFlh7KJtSWl1pKLCtvFMfU/eLVO3iRcVPPZaxUOsqp6hQ5vkgwqc+waUoOLcpSJsvymGuLkoS9gis=}
provider:
  win: azure
bot:
  automerge: true
