travis:
  secure:
    BINSTAR_TOKEN: PRmC4HIi7uCxcD++iMt5mBPHBYT4WVeSSdkFIXWPhhbwFxiyNSLDIdc+ziMxkRXvLGnl4f2Eh26u8BCsq8JsVi5psJtUBGNhrBagCXiW+iFYjpVkfNtdwTJFmV4oEM8yBdTwCOvgAq2W6EUOj1jvqJiNU2iCmboW0DxgImfA7D01K8zX5fFx5f3TaVbkxiEXt3RnygKBeVBYqWK8vCwhjt6wqj6oOocvvjSOsiONSSKxwUoz04aqpdCGTqvFa3w6N97ClQGo15mIouTDZWUK2R+jpnUFkWFE91IDCnoOetmbUtZBwuozxkYgnJPIbWmu7mD1ydtz7sGlP8x4ArzGnu7NTgqr+dlZMWoOmH2Bd0qKSieVKGq/Eal5hGpZzifGVBi/Wx2MCBYMMItz387f6ic//Q/YV04OmW/DUZJbAbXqkFGo0TGA6TDHMNu3oZyimvuluVmT37XcxJEHGRwqvN2WmFoC2jecVV/W9wA4+9kCIHzfpnjBAZkAajVBrqkhnqOgYIQ2fqYQ84k4Rgl+vTSg40H5lKz8ZFYCw3/egEyklJGPJVjIqif4e2yG0ExbO0iwblqUZjMedEa7kbzUSSMFMUpDl4gjlmcmcfheAJQqapuPQ3WRTPYV0QnP7t5Kjocv4qy8XZRSaDs6LG6i15Afr4VJ+U97TdDY1ZqGu8I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
